export const buyerSignUpFields = [
	{
		labelFor: 'FirstName',
		labelText: 'First Name',
		placeholder: 'Enter First Name',
		id: 'firstName',
		name: 'firstName',
		type: 'text',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'LastName',
		labelText: 'Last Name',
		placeholder: 'Enter Last Name',
		id: 'lastName',
		name: 'lastName',
		type: 'text',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Email',
		labelText: 'Email',
		placeholder: 'Email Address',
		id: 'email',
		name: 'email',
		type: 'email',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Password',
		labelText: 'Password',
		placeholder: 'Password',
		id: 'password',
		name: 'password',
		type: 'password',
		isRequired: true,
		autoComplete: 'true',
	},
];

export const vendorSignUpFields = [
	{
		labelFor: 'FirstName',
		labelText: 'First Name',
		placeholder: 'Enter First Name',
		id: 'firstName',
		name: 'firstName',
		type: 'text',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'LastName',
		labelText: 'Last Name',
		placeholder: 'Enter Last Name',
		id: 'lastName',
		name: 'lastName',
		type: 'text',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Email',
		labelText: 'Email',
		placeholder: 'Email Address',
		id: 'email',
		name: 'email',
		type: 'email',
		isRequired: true,
		autoComplete: 'true',
	},
];

export const userloginFields = [
	{
		labelFor: 'Email',
		labelText: 'Email',
		placeholder: 'Email Address',
		id: 'email',
		name: 'email',
		type: 'email',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Password',
		labelText: 'Password',
		placeholder: 'Password',
		id: 'password',
		name: 'password',
		type: 'password',
		isRequired: true,
		autoComplete: 'true',
	},
];

export const createProductField = [
	{
		labelFor: 'Product Owner',
		labelText: 'Product Owner',
		placeholder: 'Owner',
		id: 'productOwner',
		name: 'owner',
		type: 'text',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Product Name',
		labelText: 'Product Name',
		placeholder: 'Product name',
		id: 'productName',
		name: 'productName',
		type: 'text',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Product Price',
		labelText: 'Product Price',
		placeholder: 'Product price',
		id: 'productPrice',
		name: 'price',
		type: 'number',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Quantity',
		labelText: 'Quantity',
		placeholder: 'number of items',
		id: 'quantity',
		name: 'quantity',
		type: 'number',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Expiry Date',
		labelText: 'Expiry Date',
		placeholder: 'select date',
		id: 'expiredDate',
		name: 'date',
		type: 'date',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Product Description',
		labelText: 'Product Description',
		placeholder: 'Description',
		id: 'productDescription',
		name: 'description',
		type: 'text',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Product Category',
		labelText: 'Product Category',
		placeholder: 'category',
		id: 'category',
		name: 'category',
		type: 'text',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Bonus',
		labelText: 'Bonus',
		placeholder: 'enter amount here',
		id: 'bonus',
		name: 'bonus',
		type: 'number',
		isRequired: true,
		autoComplete: 'true',
	},
];
