export const buyerSignUpFields = [
	{
		labelFor: 'FirstName',
		labelText: 'First Name',
		placeholder: 'Enter First Name',
		id: 'firstName',
		name: 'firstName',
		type: 'text',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'LastName',
		labelText: 'Last Name',
		placeholder: 'Enter Last Name',
		id: 'lastName',
		name: 'lastName',
		type: 'text',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Email',
		labelText: 'Email',
		placeholder: 'Email Address',
		id: 'email',
		name: 'email',
		type: 'email',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Password',
		labelText: 'Password',
		placeholder: 'Password',
		id: 'password',
		name: 'password',
		type: 'password',
		isRequired: true,
		autoComplete: 'true',
	},
];

export const vendorSignUpFields = [
	{
		labelFor: 'FirstName',
		labelText: 'First Name',
		placeholder: 'Enter First Name',
		id: 'firstName',
		name: 'firstName',
		type: 'text',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'LastName',
		labelText: 'Last Name',
		placeholder: 'Enter Last Name',
		id: 'lastName',
		name: 'lastName',
		type: 'text',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Email',
		labelText: 'Email',
		placeholder: 'Email Address',
		id: 'email',
		name: 'email',
		type: 'email',
		isRequired: true,
		autoComplete: 'true',
	},
];
