export const buyerSignUpFields = [
	{
		labelFor: 'FirstName',
		labelText: 'First Name',
		placeholder: 'Enter First Name',
		id: 'firstName',
		name: 'firstName',
		type: 'text',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'LastName',
		labelText: 'Last Name',
		placeholder: 'Enter Last Name',
		id: 'lastName',
		name: 'lastName',
		type: 'text',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Email',
		labelText: 'Email',
		placeholder: 'Email Address',
		id: 'email',
		name: 'email',
		type: 'email',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Password',
		labelText: 'Password',
		placeholder: 'Password',
		id: 'password',
		name: 'password',
		type: 'password',
		isRequired: true,
		autoComplete: 'true',
	},
];
export const userloginFields = [
	{
		labelFor: 'Email',
		labelText: 'Email',
		placeholder: 'Email Address',
		id: 'email',
		name: 'email',
		type: 'email',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Password',
		labelText: 'Password',
		placeholder: 'Password',
		id: 'password',
		name: 'password',
		type: 'password',
		isRequired: true,
		autoComplete: 'true',
	},
];

export const vendorSignUpFields = [
	{
		labelFor: 'FirstName',
		labelText: 'First Name',
		placeholder: 'Enter First Name',
		id: 'firstName',
		name: 'firstName',
		type: 'text',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'LastName',
		labelText: 'Last Name',
		placeholder: 'Enter Last Name',
		id: 'lastName',
		name: 'lastName',
		type: 'text',
		isRequired: true,
		autoComplete: 'true',
	},
	{
		labelFor: 'Email',
		labelText: 'Email',
		placeholder: 'Email Address',
		id: 'email',
		name: 'email',
		type: 'email',
		isRequired: true,
		autoComplete: 'true',
	},
];

export const updateBuyerProfileFields = [
	{
		labelFor: 'shippingAddress',
		labelText: 'Shipping Address',
		placeholder: 'Shipping Address',
		id: 'shipingAddress',
		name: 'shipingAddress',
		type: 'text',
		isRequired: true,
		autoComplete: 'false',
	},
	{
		labelFor: 'paymentMethod',
		labelText: 'Payment Method',
		placeholder: 'Payment Method',
		id: 'paymentMethod',
		name: 'paymentMethod',
		type: 'text',
		isRequired: true,
		autoComplete: 'false',
	},
	{
		labelFor: 'preferredCurency',
		labelText: 'Preferred Currency',
		placeholder: 'Preferred Currency',
		id: 'preferredCurency',
		name: 'preferredCurency',
		type: 'text',
		isRequired: true,
		autoComplete: 'false',
	},
	{
		labelFor: 'state',
		labelText: 'State',
		placeholder: 'State',
		id: 'state',
		name: 'state',
		type: 'text',
		isRequired: true,
		autoComplete: 'false',
	},
	{
		labelFor: 'city',
		labelText: 'City',
		placeholder: 'City',
		id: 'city',
		name: 'city',
		type: 'text',
		isRequired: true,
		autoComplete: 'false',
	},
	{
		labelFor: 'postalCode',
		labelText: 'Postal Code',
		placeholder: 'Postal Code',
		id: 'postalCode',
		name: 'postalCode',
		type: 'text',
		isRequired: true,
		autoComplete: 'false',
	},
];

export const updateVendorProfileFields = [
	{
		labelFor: 'businessName',
		labelText: 'Business Name ',
		placeholder: 'Business Name',
		id: 'businessName',
		name: 'businessName',
		type: 'text',
		isRequired: true,
		autoComplete: 'false',
	},
	{
		labelFor: 'businessAddress',
		labelText: 'Business Address',
		placeholder: 'Business Address',
		id: 'businessAddress',
		name: 'businessAddress',
		type: 'text',
		isRequired: true,
		autoComplete: 'false',
	},
	{
		labelFor: 'accountNumber',
		labelText: 'Account Number',
		placeholder: 'Account Number',
		id: 'accountNumber',
		name: 'accountNumber',
		type: 'text',
		isRequired: true,
		autoComplete: 'false',
	},
	{
		labelFor: 'taxId',
		labelText: 'Tax Id',
		placeholder: 'Tax Id',
		id: 'taxIdNumber',
		name: 'taxIdNumber',
		type: 'text',
		isRequired: true,
		autoComplete: 'false',
	},
	{
		labelFor: 'typeOfProducts',
		labelText: 'Type Of Products',
		placeholder: 'Type Of Products',
		id: 'typeOfProducts',
		name: 'typeOfProducts',
		type: 'text',
		isRequired: true,
		autoComplete: 'false',
	},
	{
		labelFor: 'preferredCurency',
		labelText: 'Preferred Currency',
		placeholder: 'Preferred Currency',
		id: 'preferredCurency',
		name: 'preferredCurency',
		type: 'text',
		isRequired: true,
		autoComplete: 'false',
	},
	{
		labelFor: 'state',
		labelText: 'State',
		placeholder: 'State',
		id: 'state',
		name: 'state',
		type: 'text',
		isRequired: true,
		autoComplete: 'false',
	},
	{
		labelFor: 'city',
		labelText: 'City',
		placeholder: 'City',
		id: 'city',
		name: 'city',
		type: 'text',
		isRequired: true,
		autoComplete: 'false',
	},
	{
		labelFor: 'postalCode',
		labelText: 'Postal Code',
		placeholder: 'Postal Code',
		id: 'postalCode',
		name: 'postalCode',
		type: 'text',
		isRequired: true,
		autoComplete: 'false',
	},
];
export const genderOptions = [
	{ value: 'male', text: 'male' },
	{ value: 'female', text: 'female' },
	{ value: 'other', text: 'other' },
];
